import type { StrapiApp } from "@strapi/strapi/admin";

export default {
  config: {
    locales: [
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      "es",
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      // 'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      // 'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
    translations: {
      es: {
        "app.components.LeftMenu.navbrand.title": "Panel de administración",
        "app.components.LeftMenu.navbrand.workplace": "Gestión de contenido",
        "app.components.LeftMenu.logout": "Cerrar sesión",
        "app.components.LeftMenu.profile": "Perfil",
        "app.components.HomePage.welcome":
          "Bienvenido al panel de administración",
        "Auth.form.email.label": "Correo electrónico",
        "Auth.form.password.label": "Contraseña",
        "Auth.form.firstname.label": "Nombre",
        "Auth.form.lastname.label": "Apellido",
        "Auth.form.rememberMe.label": "Recordarme",
        "Auth.form.button.login": "Iniciar sesión",
        "Auth.form.button.register": "Registrarse",
        "Auth.form.button.forgot-password": "Olvidé mi contraseña",
        "Auth.form.welcome.title": "Bienvenido a Strapi",
        "Auth.form.welcome.subtitle": "Inicia sesión en tu cuenta",
        "Auth.form.error.email.provide":
          "Por favor, ingrese su correo electrónico",
        "Auth.form.error.password.provide": "Por favor, ingrese su contraseña",
        "Auth.form.error.email.invalid": "El correo electrónico no es válido",
        "global.save": "Guardar",
        "global.cancel": "Cancelar",
        "global.delete": "Eliminar",
        "global.edit": "Editar",
        "global.create": "Crear",
        "global.confirm": "Confirmar",
        "global.continue": "Continuar",
        "global.close": "Cerrar",
        "global.back": "Atrás",
        "global.actions": "Acciones",
        "global.settings": "Configuraciones",
        "global.upload": "Subir",
        "global.download": "Descargar",
        "global.search": "Buscar",
        "global.add": "Agregar",
        "global.remove": "Eliminar",
        "global.ok": "Aceptar",
        "global.name": "Nombre",
        "global.description": "Descripción",
        "global.enabled": "Habilitado",
        "global.disabled": "Deshabilitado",
        "global.true": "Sí",
        "global.false": "No",
        "global.type": "Tipo",
        "global.required": "Obligatorio",
        "global.optional": "Opcional",
        "app.components.Users.MagicLink.connect": "Conectar con enlace mágico",
        "app.components.Users.MagicLink.linkReady":
          "Tu enlace mágico está listo",
        "app.components.Users.MagicLink.copy": "Copiar enlace",
        "content-manager.containers.ListPage.displayedFields":
          "Campos mostrados",
        "content-manager.containers.ListPage.list.empty":
          "No hay contenido todavía",
        "content-manager.containers.EditView.add.new": "Agregar nuevo registro",
        "content-manager.containers.EditView.info.title":
          "Detalles del contenido",
        "content-manager.containers.EditView.info.text":
          "Administra los campos y su información",
        "content-manager.containers.EditView.validation.error":
          "Ocurrió un error de validación",
        "content-manager.containers.SettingsView.pluginHeader.title":
          "Configuración del tipo de contenido",
        "content-manager.containers.SettingsView.pluginHeader.description":
          "Define permisos y comportamiento",
        "components.Input.error.validation.required":
          "Este campo es obligatorio",
        "components.Input.error.validation.email":
          "Debe ser un correo electrónico válido",
        "components.Input.error.validation.minLength":
          "Debe tener al menos {{min}} caracteres",
        "components.Input.error.validation.maxLength":
          "Debe tener como máximo {{max}} caracteres",
        "components.Input.error.validation.regex": "Formato inválido",
        "content-type-builder.menu.section.models.name": "Tipos de contenido",
        "content-type-builder.menu.section.components.name": "Componentes",
        "content-type-builder.plugin.description.long":
          "Crea y gestiona estructuras de contenido dinámicas",
        "content-type-builder.plugin.name": "Constructor de tipos de contenido",
        "content-type-builder.form.button.create":
          "Crear nuevo tipo de contenido",
        "content-type-builder.form.button.save": "Guardar cambios",
        "content-type-builder.form.attribute.text": "Texto",
        "content-type-builder.form.attribute.richtext": "Texto enriquecido",
        "content-type-builder.form.attribute.boolean": "Booleano",
        "content-type-builder.form.attribute.date": "Fecha",
        "content-type-builder.form.attribute.media": "Archivo multimedia",
        "content-type-builder.form.attribute.number": "Número",
        "content-type-builder.form.attribute.enumeration": "Enumeración",
        "content-type-builder.form.attribute.json": "JSON",
        "content-type-builder.form.attribute.password": "Contraseña",
        "content-type-builder.form.attribute.email": "Correo electrónico",
        "content-type-builder.form.attribute.uid": "Identificador único (UID)",
        "content-type-builder.form.attribute.relation": "Relación",
        "content-type-builder.form.button.add.field": "Agregar campo",
        "plugin.content-manager": "Gestor de contenido",
        "plugin.content-type-builder": "Constructor de tipos de contenido",
        "plugin.upload": "Archivos multimedia",
        "plugin.users-permissions": "Usuarios y permisos",
        "users-permissions.PluginHeader.title": "Usuarios y Permisos",
        "users-permissions.RolePage.create": "Crear nuevo rol",
        "users-permissions.RolePage.name": "Nombre del rol",
        "users-permissions.RolePage.description": "Descripción del rol",
        "users-permissions.RolePage.permissions": "Permisos",
        "users-permissions.RolePage.users": "Usuarios",
        "users-permissions.Permission.settings": "Configuración de permisos",
        "users-permissions.Permission.select.all": "Seleccionar todo",
        "users-permissions.Permission.unselect.all": "Deseleccionar todo",
        "users-permissions.Permission.action.create": "Crear",
        "users-permissions.Permission.action.read": "Leer",
        "users-permissions.Permission.action.update": "Actualizar",
        "users-permissions.Permission.action.delete": "Eliminar",
        "media-library.header.title": "Biblioteca multimedia",
        "media-library.header.actions.upload": "Subir archivos",
        "media-library.header.actions.add-folder": "Nueva carpeta",
        "media-library.empty.title": "No hay archivos todavía",
        "media-library.empty.description":
          "Sube imágenes, videos o documentos para comenzar",
        "notification.success.saved": "Guardado exitosamente",
        "notification.success.created": "Creado exitosamente",
        "notification.success.deleted": "Eliminado exitosamente",
        "notification.error": "Ocurrió un error",
        "notification.warning": "Advertencia",
        "notification.info": "Información",
        "settings.profile.header.title": "Perfil del usuario",
        "settings.profile.form.email": "Correo electrónico",
        "settings.profile.form.firstname": "Nombre",
        "settings.profile.form.lastname": "Apellido",
        "settings.profile.form.password": "Contraseña",
        "settings.profile.form.language": "Idioma de la interfaz",
        "settings.profile.form.save": "Guardar cambios",
        "settings.application.title": "Configuración general",
        "settings.application.description":
          "Parámetros globales de la aplicación",
        "settings.roles.title": "Roles y permisos",
        "settings.roles.description":
          "Gestiona los roles de usuario y sus accesos",
        "settings.webhooks.title": "Webhooks",
        "settings.webhooks.description":
          "Configura los webhooks para recibir eventos",
        "settings.apiTokens.title": "Tokens de API",
        "settings.apiTokens.description":
          "Gestiona tus claves de acceso a la API",
        "settings.email.title": "Configuración de correo",
        "settings.email.description":
          "Configura los proveedores y plantillas de correo",
        "users-permissions.Users.header": "Usuarios",
        "users-permissions.Users.add": "Agregar nuevo usuario",
        "users-permissions.Users.username": "Nombre de usuario",
        "users-permissions.Users.email": "Correo electrónico",
        "users-permissions.Users.role": "Rol",
        "users-permissions.Users.actions": "Acciones",
        "users-permissions.Users.status": "Estado",
        "users-permissions.Users.enabled": "Activo",
        "users-permissions.Users.disabled": "Inactivo",
        "users-permissions.Users.confirmed": "Confirmado",
        "users-permissions.Users.not-confirmed": "No confirmado",
        "global.about": "Acerca de",
        "global.title": "Título",
        "global.createdAt": "Creado el",
        "global.updatedAt": "Actualizado el",
        "global.publishedAt": "Publicado el",
        "global.draft": "Borrador",
        "global.publish": "Publicar",
        "global.unpublish": "Despublicar",
        "global.contentType": "Tipo de contenido",
        "global.collectionType": "Colección",
        "global.singleType": "Tipo único",
        "global.field": "Campo",
        "global.fields": "Campos",
        "global.value": "Valor",
        "global.language": "Idioma",
        "global.content": "Contenido",
        "global.media": "Medios",
        "global.user": "Usuario",
        "global.users": "Usuarios",
        "global.role": "Rol",
        "global.roles": "Roles",
        "global.permission": "Permiso",
        "global.permissions": "Permisos",
        "global.email": "Correo electrónico",
        "global.password": "Contraseña",
      },
    },
  },
  bootstrap(app: StrapiApp) {
    console.log(app);
  },
};
